services:
  web:
    build: .
    command: /app/start.sh
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=local_database_editor.settings
      - SQLITE_DB_PATH=/app/data/db.sqlite3
    image: jaelevy/local-database-editor:0.1
    ports:
      - '8088:8088'
    volumes:
      - ./data:/app/data
